name: build

on: [push, pull_request]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:

      fail-fast: false

      matrix:

        os: [windows-latest]

        build_type: [Release]

        enable_ui: [on]

        include:

          - os: windows-latest

            build_type: Release

            enable_ui: on

    steps:

    - uses: actions/checkout@v3

      with:

        submodules: &#39;recursive&#39;

    - name: ccache

      uses: hendrikmuhs/ccache-action@v1

      if: runner.os == &#39;Linux&#39;

      with:

        key: ${{ matrix.os }}-${{ matrix.enable_ui }}

    - uses: seanmiddleditch/gha-setup-ninja@master

    - uses: ilammy/msvc-dev-cmd@v1

      if: runner.os == &#39;Windows&#39;

    - name: Install Dependencies

      shell: bash

      run: |

        if [[ &#34;${{ runner.os }}&#34; == &#34;Linux&#34; ]] ; then

          sudo apt-get update -qq

          sudo apt-get install -y \

            libx11-dev libxcursor-dev libxi-dev

        fi

    - name: Generating Makefiles

      shell: bash

      run: |

        if [[ &#34;${{ runner.os }}&#34; == &#34;Windows&#34; ]] ; then

          export enable_ccache=off

        else

          export enable_ccache=on

        fi

        curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --output skia.zip

        7z x skia.zip

        cmake -S . -B build -G Ninja \

          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \

          -DENABLE_UI=${{ matrix.enable_ui }} \
